### ISSUE TITLE
Maximum downward speed not working

### ISSUE THREAD

**Issue by dominikfehr** [444A49/minifindings#2]
Hey, thanks for your reserach.

I wonder which firmware you used, since the maximum downward speed parameter doesn't seem to work on .500, .400 and .300?

Other tested parameters like upward speed work fine.

**Comment by 444A49** [comment]
All my test are based on firmware .200

**Comment by dominikfehr** [comment]
In the meantime I have tested .200, too. I Can not confirm the downward speed on this firmware either. Probably the Android app is responsible somehow :/ Could you re-check and confirm that it works for you? Thanks in advance

**Comment by 444A49** [comment]
App shouldn't have any impact on the drone's param. Remember that you need to setup `vert_vel_down_adding_max_0` as well, as this governs the general downward speed.

Mine is on .200 and I get 40km/h when pulling the stick down.

**Comment by dominikfehr** [comment]
Thanks I'll try that! For upward it worked directly so I didn't check if it required more values to be set.
