### ISSUE TITLE
NFZ Restrictions GPS disabled

### ISSUE THREAD

**Issue by albertoiglesias2001** [444A49/minifindings#3]
Hello my friend, I have one manic mini too and I'm living on restricted zone, so, I cannot open my window and start to fligh, because when the drone get the gps signal, it's show on the app the message attached here.

I have 90 seconds before return or the drone will be start to landing.

Do you have any way to block this?  I just want to flight with my drone next to my house.

![WhatsApp Image 2020-08-15 at 00 50 53](https://user-images.githubusercontent.com/18347714/90300303-c2ea9880-de91-11ea-8735-b1e4e9236767.jpeg)

I'm developer too, so , I can do things in low level if you have some trick.

Thank you so much!!!

**Comment by 444A49** [comment]
There's nothing available yet to bypass nfz unfortunately.

**Comment by albertoiglesias2001** [comment]
ok. so sad!  I'm stuck in my home with my drone...  Thanks
