### ISSUE TITLE
Usb - ethernet

### ISSUE THREAD

**Issue by korikmate** [444A49/minifindings#5]
Hello,
I would like to ask that what port of the RC is OK for telnet connection over usb-ethernet? The standard USB and the micro also? Thanks!

**Comment by edyno** [comment]
IP = 192.168.3.10, port via putty = 23
IP of your PC for example 192.168.3.2 

It is important that the USB adapter contains the ASIX AX88772 chip. Other adapter didn't work for me.

My case:: https://www.amazon.de/-/cs/gp/product/B00MYT481C/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

**Comment by 444A49** [comment]
@edyno  is right
